version: "3.9"
services:
  command-launcher:
    environment:
      SERVER_PORT: 8000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: commands
      DB_SSLMODE: disable
    container_name: command-launcher
    build: ./
    ports:
      - '8000:8000'
    volumes:
      - ./:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: commands
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
